#!/bin/bash
#
# 03-network-stack — let the user choose between keeping NetworkManager
# (tuned) or switching to systemd-networkd.
#
# Default: keep NetworkManager. It works for most setups and minimises the
# lockout risk on SSH-only hosts. systemd-networkd is offered as an opt-in
# for users who observe playback dropouts (Qobuz on some hardware) or want a
# fully deterministic stack.
#
# State-aware: if the host is already on networkd and the user picks "keep
# NM", the previous switch is reverted (re-enable NM, disable networkd,
# remove tagged .network files and the wait-online drop-in).
#
# Files this module generates carry a header line so the revert can identify
# them safely without touching .network files the user wrote by hand.
#

set -euo pipefail

readonly _NET_GEN_TAG="# Generated by fedora-audiophile-setup"
readonly _NET_DIR="/etc/systemd/network"
readonly _NET_WAIT_DROPIN_DIR="/etc/systemd/system/systemd-networkd-wait-online.service.d"
readonly _NET_WAIT_DROPIN="${_NET_WAIT_DROPIN_DIR}/10-limit-to-wan.conf"

log_step "Network stack: NetworkManager (tuned) or systemd-networkd"

# --- State detection ------------------------------------------------------

_net_current_stack() {
    local nm netd
    is_service_active NetworkManager     && nm=1   || nm=0
    is_service_active systemd-networkd   && netd=1 || netd=0
    if   [[ $nm -eq 1 && $netd -eq 0 ]]; then echo "NetworkManager"
    elif [[ $nm -eq 0 && $netd -eq 1 ]]; then echo "systemd-networkd"
    elif [[ $nm -eq 1 && $netd -eq 1 ]]; then echo "both"
    else                                       echo "none"
    fi
}

_net_detect_wan_iface() {
    ip -o -4 route show default 2>/dev/null | awk '{print $5; exit}'
}

# Print one iface per line: physical, ethernet (type 1), state up, not lo.
_net_physical_ethernet_ifaces() {
    local sys iface typ state
    for sys in /sys/class/net/*; do
        iface=$(basename "$sys")
        [[ "$iface" == "lo" ]] && continue
        [[ "$(readlink -f "$sys")" == *"/devices/virtual/"* ]] && continue
        typ=$(cat "${sys}/type" 2>/dev/null || echo "")
        [[ "$typ" == "1" ]] || continue
        state=$(cat "${sys}/operstate" 2>/dev/null || echo "")
        [[ "$state" == "up" ]] || continue
        echo "$iface"
    done
}

# --- Branch K: keep / restore NetworkManager (tuned) ----------------------

_net_revert_to_nm() {
    log_warn "Reverting previous switch: re-enabling NetworkManager, disabling systemd-networkd."
    run_cmd systemctl unmask NetworkManager
    run_cmd systemctl enable --now NetworkManager
    run_cmd systemctl disable --now systemd-networkd
    run_cmd systemctl disable --now systemd-networkd-wait-online.socket || true
    run_cmd systemctl disable --now systemd-networkd-wait-online.service || true

    # Remove only the .network files we generated (tagged in header).
    if [[ -d "$_NET_DIR" ]]; then
        local f
        while IFS= read -r f; do
            if head -1 "$f" 2>/dev/null | grep -qF "$_NET_GEN_TAG"; then
                log_info "Removing generated ${f}"
                run_cmd rm -f "$f"
            fi
        done < <(find "$_NET_DIR" -maxdepth 1 -name '*.network' -type f 2>/dev/null)
    fi

    if [[ -f "$_NET_WAIT_DROPIN" ]]; then
        run_cmd rm -f "$_NET_WAIT_DROPIN"
        rmdir --ignore-fail-on-non-empty "$_NET_WAIT_DROPIN_DIR" 2>/dev/null || true
    fi
    run_cmd systemctl daemon-reload
}

_net_tune_nm() {
    if ! has_package NetworkManager-tui; then
        log_info "Installing NetworkManager-tui (provides nmtui)."
        run_cmd dnf -y install NetworkManager-tui
    fi
    if is_service_enabled NetworkManager-wait-online.service; then
        log_info "Disabling NetworkManager-wait-online.service (avoids boot delays)."
        run_cmd systemctl disable NetworkManager-wait-online.service
    fi
}

_net_keep_nm() {
    local current="$1"
    case "$current" in
        systemd-networkd|both) _net_revert_to_nm ;;
        none)                  run_cmd systemctl enable --now NetworkManager ;;
        NetworkManager)        : ;;  # already there
    esac
    _net_tune_nm
    log_info "Network stack: NetworkManager (tuned)."
}

# --- Branch S: switch to systemd-networkd ---------------------------------

_net_write_dhcp_network() {
    local iface="$1" file="${_NET_DIR}/10-${iface}.network"
    log_info "Generating ${file} (DHCP)"
    cat > "$file" <<EOF
${_NET_GEN_TAG}
[Match]
Name=${iface}

[Network]
DHCP=yes
EOF
}

_net_write_static_network() {
    local iface="$1" addr="$2" gw="$3"
    local file="${_NET_DIR}/10-${iface}.network"
    log_info "Generating ${file} (static ${addr}${gw:+, gw=${gw}})"
    {
        echo "${_NET_GEN_TAG}"
        echo "[Match]"
        echo "Name=${iface}"
        echo
        echo "[Network]"
        [[ -n "$addr" ]] && echo "Address=${addr}"
        [[ -n "$gw" ]]   && echo "Gateway=${gw}"
    } > "$file"
}

_net_generate_network_files() {
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would generate one .network file per active physical ethernet interface under ${_NET_DIR}"
        return 0
    fi
    mkdir -p "$_NET_DIR"
    local iface method addr gw
    while IFS= read -r iface; do
        method=$(nmcli -t -f IPV4.METHOD device show "$iface" 2>/dev/null | cut -d: -f2 | head -1 || true)
        case "$method" in
            auto|"")
                _net_write_dhcp_network "$iface"
                ;;
            manual)
                addr=$(nmcli -t -f IP4.ADDRESS device show "$iface" 2>/dev/null | cut -d: -f2 | head -1)
                gw=$(nmcli -t -f IP4.GATEWAY device show "$iface" 2>/dev/null | cut -d: -f2 | head -1)
                _net_write_static_network "$iface" "$addr" "$gw"
                ;;
            *)
                log_warn "Skipping interface ${iface}: NM IPv4 method '${method}' not supported in v0.1. Configure ${_NET_DIR}/10-${iface}.network manually."
                ;;
        esac
    done < <(_net_physical_ethernet_ifaces)
}

_net_limit_wait_online() {
    local wan
    wan=$(_net_detect_wan_iface)
    if [[ -z "$wan" ]]; then
        log_warn "Could not detect WAN interface (no default route). Skipping networkd-wait-online limit."
        return 0
    fi
    log_info "Limiting systemd-networkd-wait-online to ${wan}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_NET_WAIT_DROPIN}"
        return 0
    fi
    mkdir -p "$_NET_WAIT_DROPIN_DIR"
    cat > "$_NET_WAIT_DROPIN" <<EOF
${_NET_GEN_TAG}
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i ${wan}
EOF
    run_cmd systemctl daemon-reload
}

_net_switch_to_networkd() {
    local current="$1"
    if [[ "$current" == "systemd-networkd" ]]; then
        log_info "Already on systemd-networkd — re-generating config if needed."
    fi

    log_warn "Switching from NetworkManager to systemd-networkd."
    log_warn "If your generated config is wrong you may LOSE NETWORK ACCESS — make sure you have console (not just SSH) access before continuing."
    if ! ask_yes_no "Continue?" N; then
        log_info "Aborted by user — leaving the network stack untouched."
        return 0
    fi

    _net_generate_network_files
    _net_limit_wait_online

    run_cmd systemctl enable --now systemd-networkd
    run_cmd systemctl enable --now systemd-resolved
    if [[ "$current" != "none" ]]; then
        run_cmd systemctl disable --now NetworkManager
        run_cmd systemctl mask NetworkManager
    fi
    log_info "Network stack: systemd-networkd."
}

# --- Dispatch -------------------------------------------------------------

_current_stack=$(_net_current_stack)
log_info "Detected current network stack: ${_current_stack}"

if [[ "$_current_stack" == "both" ]]; then
    log_warn "Both NetworkManager and systemd-networkd are active — this is a broken state. The module will resolve it based on your choice below."
fi

echo
echo "Network stack options:"
echo "  K) Keep NetworkManager (tuned)   [default — safe, supports nmtui]"
echo "  S) Switch to systemd-networkd    [deterministic, opt-in]"
echo "  N) Skip — do not touch the network stack"
echo
read -r -p "Choose [K/s/n] " _choice
_choice="${_choice:-K}"

case "${_choice^^}" in
    K) _net_keep_nm "$_current_stack" ;;
    S) _net_switch_to_networkd "$_current_stack" ;;
    N) log_info "Skipping — network stack left as-is." ;;
    *) log_error "Invalid choice: ${_choice}"; exit 1 ;;
esac
