#!/bin/bash
#
# 06-cpu-states — pin CPU to performance state, disable turbo/boost, and
# disable deep idle states.
#
# Installs a single systemd oneshot service that on every boot writes to
# /sys/devices/system/cpu/... to:
#   1. Set scaling_governor=performance on every CPU
#   2. Disable turbo/boost (Intel pstate no_turbo, or generic cpufreq boost)
#   3. Disable c-states deeper than C0/C1 on every CPU
#
# Independent of the DRUP tuner — both can coexist safely (they write the
# same values). Idempotent: re-running rewrites the service / script and
# restarts the unit so the latest content is applied immediately.
#

set -euo pipefail

readonly _CPU_GEN_TAG="# Generated by fedora-audiophile-setup"
readonly _CPU_SERVICE="audiophile-cpu-states.service"
readonly _CPU_SERVICE_PATH="/etc/systemd/system/${_CPU_SERVICE}"
readonly _CPU_SCRIPT="/usr/local/sbin/audiophile-cpu-states.sh"

log_step "CPU performance pinning (governor / no_turbo / c-states)"

_cpu_write_script() {
    log_info "Installing ${_CPU_SCRIPT}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_CPU_SCRIPT}"
        return 0
    fi
    mkdir -p "$(dirname "$_CPU_SCRIPT")"
    cat > "$_CPU_SCRIPT" <<'SCRIPT_EOF'
#!/bin/bash
# Generated by fedora-audiophile-setup — boot-time CPU tuning.
# Best-effort: missing sysfs nodes are skipped silently so the same script
# runs on any x86_64 host (Intel pstate, AMD, ACPI cpufreq).

set -u

# 1. Governor = performance on every CPU
for f in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    [[ -w "$f" ]] && echo performance > "$f" 2>/dev/null || true
done

# 2. Disable turbo / boost. Intel pstate exposes no_turbo; everything else
#    (AMD pstate, acpi-cpufreq) exposes cpufreq/boost.
if [[ -w /sys/devices/system/cpu/intel_pstate/no_turbo ]]; then
    echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo 2>/dev/null || true
elif [[ -w /sys/devices/system/cpu/cpufreq/boost ]]; then
    echo 0 > /sys/devices/system/cpu/cpufreq/boost 2>/dev/null || true
fi

# 3. Disable c-states deeper than C0/C1 (state2 and beyond)
for d in /sys/devices/system/cpu/cpu*/cpuidle; do
    [[ -d "$d" ]] || continue
    for s in "$d"/state[2-9]*; do
        [[ -w "$s/disable" ]] && echo 1 > "$s/disable" 2>/dev/null || true
    done
done

exit 0
SCRIPT_EOF
    chmod +x "$_CPU_SCRIPT"
}

_cpu_write_service() {
    log_info "Installing ${_CPU_SERVICE_PATH}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_CPU_SERVICE_PATH}"
        return 0
    fi
    cat > "$_CPU_SERVICE_PATH" <<EOF
${_CPU_GEN_TAG}
[Unit]
Description=Audiophile CPU performance pinning (governor, no_turbo, c-states)
After=multi-user.target

[Service]
Type=oneshot
ExecStart=${_CPU_SCRIPT}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
}

_cpu_write_script
_cpu_write_service
run_cmd systemctl daemon-reload
run_cmd systemctl enable "$_CPU_SERVICE"
# Use restart (not start) so a re-run after editing the script picks up the
# new content even when the unit is already active with RemainAfterExit=yes.
run_cmd systemctl restart "$_CPU_SERVICE"

log_info "CPU performance pinning service installed and active."
