#!/bin/bash
#
# 07-sysctl-network — bump global kernel socket-buffer limits.
#
# Scope strictly limited to host-wide knobs in /etc/sysctl.d/. Per-interface
# tuning (MTU, ethtool) is intentionally NOT done here: on a Diretta host
# there are typically two NICs (WAN/LAN at MTU 1500, Diretta point-to-point
# up to MTU 16128), and only the install-drup / install-slim2diretta modules
# know which NIC is which. They handle MTU and ethtool there.
#

set -euo pipefail

readonly _SYSCTL_GEN_TAG="# Generated by fedora-audiophile-setup"
readonly _SYSCTL_FILE="/etc/sysctl.d/99-audiophile-network.conf"

log_step "Kernel socket buffer limits"

_sysctl_write_file() {
    log_info "Writing ${_SYSCTL_FILE}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_SYSCTL_FILE}"
        return 0
    fi
    cat > "$_SYSCTL_FILE" <<EOF
${_SYSCTL_GEN_TAG}
# Per-socket buffer headroom. Audio streaming itself is low-bandwidth, but
# bursty paths and jumbo frames benefit from larger buffers. Values are
# conservative for a dedicated audio host (~16 MB max, ~4 MB default).

net.core.rmem_max     = 16777216
net.core.wmem_max     = 16777216
net.core.rmem_default =  4194304
net.core.wmem_default =  4194304

# Larger optmem_max gives socket ancillary data (cmsg) room — relevant on
# multicast / hw-timestamping paths that Diretta-style stacks may rely on.
net.core.optmem_max   = 65536

# Larger netdev backlog absorbs short bursts between NIC IRQ and userland
# reads, smoothing out latency under contention.
net.core.netdev_max_backlog = 5000
EOF
}

_sysctl_write_file
run_cmd sysctl --system

log_info "Socket buffer limits applied (${_SYSCTL_FILE})."
