#!/bin/bash
#
# 10-install-drup — orchestrate the DirettaRendererUPnP install.
#
# Flow (asks Y/N upfront — module is optional):
#   1. Detect SUDO_USER (DRUP install.sh refuses root)
#   2. Detect Diretta SDK under /home/$SUDO_USER/DirettaHostSDK_*
#      (SDK download is manual — licence "personal use only" — diretta.link)
#   3. Install ethtool (used by start-renderer at runtime)
#   4. Interactive NIC selection: which NIC is Diretta-side (audio target),
#      which is control-point side (UPnP — Roon, Audirvana, etc.)
#   5. Ask MTU for the Diretta NIC (1500 / 9000 / 16128)
#   6. Persist MTU on the Diretta NIC: always write a .link drop-in (read by
#      systemd-udevd at coldplug), and additionally set the MTU via nmcli on
#      the active NM connection profile if NetworkManager is the live stack —
#      otherwise NM can override the value udev applied.
#   7. git clone DRUP into $HOME/DirettaRendererUPnP (as $SUDO_USER)
#   8. Run ./install.sh as $SUDO_USER in a real TTY (~30 min for FFmpeg build);
#      skipped if the binary already exists
#   9. Run systemd/install-systemd.sh as root (copies binary, conf, service)
#  10. Post-process /etc/default/diretta-renderer: set INTERFACE,
#      TARGET_INTERFACE, TARGET
#  11. systemctl enable (don't start — service waits for next reboot once
#      kernel-rt and the new NIC MTU are active)
#

set -euo pipefail

readonly _DRUP_REPO_URL="https://github.com/cometdom/DirettaRendererUPnP.git"
readonly _DRUP_CONF_FILE="/etc/default/diretta-renderer"
readonly _DRUP_SERVICE="diretta-renderer.service"
readonly _DRUP_GEN_TAG="# Generated by fedora-audiophile-setup"

log_step "Install DirettaRendererUPnP"

if ! ask_yes_no "Install DirettaRendererUPnP?" Y; then
    log_info "Skipping DRUP install."
    return 0 2>/dev/null || exit 0
fi

# --- 1. Detect the unprivileged user that ran sudo ----------------------

if [[ -z "${SUDO_USER:-}" || "${SUDO_USER}" == "root" ]]; then
    log_error "DRUP's install.sh refuses to run as root."
    log_error "Please launch this wizard via 'sudo' from a regular user account (not a direct root login)."
    exit 1
fi
_drup_user="$SUDO_USER"
_drup_home=$(getent passwd "$_drup_user" | cut -d: -f6)
if [[ -z "$_drup_home" || ! -d "$_drup_home" ]]; then
    log_error "Cannot resolve home directory of user '${_drup_user}'."
    exit 1
fi
log_info "DRUP will be built as user '${_drup_user}' (home: ${_drup_home})."

# --- 2. Find the manually-downloaded Diretta SDK ------------------------

_drup_sdk=$(find "$_drup_home" -maxdepth 1 -type d -name 'DirettaHostSDK_*' 2>/dev/null \
    | sort -V | tail -1)
if [[ -z "$_drup_sdk" ]]; then
    log_error "Diretta SDK not found under ${_drup_home}/DirettaHostSDK_*"
    log_error ""
    log_error "The SDK is licensed 'for personal use only' and must be downloaded manually:"
    log_error "  1. Visit https://www.diretta.link/hostsdk.html"
    log_error "  2. Download the latest DirettaHostSDK_*.tar.zst"
    log_error "  3. Copy it to ${_drup_home}/ on this host"
    log_error "  4. Extract:  tar --zstd -xf DirettaHostSDK_*.tar.zst"
    log_error "  5. Re-run:   sudo ./setup.sh --only install-drup"
    exit 1
fi
log_info "Found Diretta SDK: ${_drup_sdk}"

# --- 3. Install root-side runtime prerequisite (ethtool) ----------------

if ! has_package ethtool; then
    log_info "Installing ethtool (used by start-renderer for link tuning)"
    run_cmd dnf -y install ethtool
fi

# --- 4. NIC selection ----------------------------------------------------

# Physical ethernet interfaces in operstate=up.
_drup_eth_ifaces_up() {
    local sys iface typ state
    for sys in /sys/class/net/*; do
        iface=$(basename "$sys")
        [[ "$iface" == "lo" ]] && continue
        [[ "$(readlink -f "$sys")" == *"/devices/virtual/"* ]] && continue
        typ=$(cat "${sys}/type" 2>/dev/null || echo "")
        [[ "$typ" == "1" ]] || continue
        state=$(cat "${sys}/operstate" 2>/dev/null || echo "")
        [[ "$state" == "up" ]] || continue
        echo "$iface"
    done
}

_drup_pick_iface() {
    local prompt="$1"; shift
    local choices=("$@")
    echo
    echo "${prompt}"
    local i
    for i in "${!choices[@]}"; do
        echo "  $((i+1))) ${choices[i]}"
    done
    while true; do
        read -r -p "Number [1]: " _pick
        _pick="${_pick:-1}"
        if [[ "$_pick" =~ ^[1-9][0-9]*$ ]] && (( _pick >= 1 && _pick <= ${#choices[@]} )); then
            echo "${choices[$((_pick-1))]}"
            return 0
        fi
        echo "Invalid choice."
    done
}

mapfile -t _drup_ifaces < <(_drup_eth_ifaces_up)
if [[ ${#_drup_ifaces[@]} -eq 0 ]]; then
    log_error "No active physical ethernet interface — cannot configure DRUP."
    exit 1
elif [[ ${#_drup_ifaces[@]} -eq 1 ]]; then
    _drup_diretta_iface="${_drup_ifaces[0]}"
    _drup_control_iface="${_drup_ifaces[0]}"
    log_info "Single NIC '${_drup_diretta_iface}' will serve both UPnP (control points) and Diretta target."
else
    _drup_diretta_iface=$(_drup_pick_iface "Which NIC is connected to the Diretta target (audio side)?" "${_drup_ifaces[@]}")
    if [[ ${#_drup_ifaces[@]} -eq 2 ]]; then
        for _iface in "${_drup_ifaces[@]}"; do
            [[ "$_iface" != "$_drup_diretta_iface" ]] && _drup_control_iface="$_iface"
        done
    else
        # 3+ NICs: ask explicitly
        _drup_remaining=()
        for _iface in "${_drup_ifaces[@]}"; do
            [[ "$_iface" != "$_drup_diretta_iface" ]] && _drup_remaining+=("$_iface")
        done
        _drup_control_iface=$(_drup_pick_iface "Which NIC is the control-point side (UPnP: Audirvana/Roon)?" "${_drup_remaining[@]}")
    fi
    log_info "Diretta NIC:       ${_drup_diretta_iface}"
    log_info "Control-point NIC: ${_drup_control_iface}"
fi

# --- 5. MTU choice for the Diretta NIC -----------------------------------

echo
echo "MTU on the Diretta NIC '${_drup_diretta_iface}':"
echo "  1) 1500   (standard)"
echo "  2) 9000   (jumbo, recommended)"
echo "  3) 16128  (max — only if the Diretta target supports it)"
read -r -p "Number [2]: " _drup_mtu_choice
case "${_drup_mtu_choice:-2}" in
    1) _drup_mtu=1500 ;;
    2|"") _drup_mtu=9000 ;;
    3) _drup_mtu=16128 ;;
    *) log_error "Invalid MTU choice: ${_drup_mtu_choice}"; exit 1 ;;
esac

# --- 6. Persist MTU on the Diretta NIC -----------------------------------

_drup_persist_mtu() {
    local iface="$1" mtu="$2"
    local link_file="/etc/systemd/network/50-audiophile-${iface}-mtu.link"

    # Always write the systemd-udevd .link drop-in (applied at coldplug).
    log_info "Writing ${link_file} (MTUBytes=${mtu})"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${link_file}"
    else
        mkdir -p /etc/systemd/network
        cat > "$link_file" <<EOF
${_DRUP_GEN_TAG}
[Match]
OriginalName=${iface}

[Link]
MTUBytes=${mtu}
EOF
    fi

    # If NetworkManager is the live stack, also set the MTU on its active
    # connection profile — otherwise NM can override what udev applied.
    if is_service_active NetworkManager && command -v nmcli >/dev/null 2>&1; then
        local conn
        conn=$(nmcli -t -f NAME,DEVICE connection show --active 2>/dev/null \
            | awk -F: -v d="$iface" '$2==d {print $1; exit}')
        if [[ -n "$conn" ]]; then
            log_info "Setting MTU ${mtu} on NetworkManager connection '${conn}'"
            run_cmd nmcli connection modify "$conn" 802-3-ethernet.mtu "$mtu"
        else
            log_warn "No active NM connection found for ${iface}; relying on the udev .link drop-in only."
        fi
    fi
}

_drup_persist_mtu "$_drup_diretta_iface" "$_drup_mtu"

# --- 7. git clone DRUP as the unprivileged user --------------------------

_drup_dir="${_drup_home}/DirettaRendererUPnP"
if [[ -d "${_drup_dir}/.git" ]]; then
    log_info "DRUP repo already cloned at ${_drup_dir}"
else
    log_info "Cloning DRUP repo to ${_drup_dir} (as ${_drup_user})"
    run_cmd sudo -u "$_drup_user" git clone "$_DRUP_REPO_URL" "$_drup_dir"
fi

# --- 8. Run DRUP install.sh as the user (TTY-direct, ~30 min) ------------

_drup_binary="${_drup_dir}/bin/DirettaRendererUPnP"
if [[ -f "$_drup_binary" ]]; then
    log_info "DRUP binary already built at ${_drup_binary} — skipping ./install.sh."
else
    log_warn "About to run DRUP ./install.sh as user '${_drup_user}'."
    log_warn "It compiles FFmpeg from source — expect ~30 minutes. Answer its prompts."
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would execute as ${_drup_user}: cd ${_drup_dir} && ./install.sh"
    else
        # Direct exec (no run_cmd / tee pipe) so install.sh keeps its TTY.
        # -i = login shell so PATH/HOME are clean for the user.
        sudo -u "$_drup_user" -i bash -c "cd '${_drup_dir}' && ./install.sh"
    fi
fi

# --- 9. Install the systemd service via DRUP's own installer -------------

log_info "Running ${_drup_dir}/systemd/install-systemd.sh (root) to deploy /opt/diretta-renderer-upnp + service unit."
if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
    log_info "DRY-RUN: would execute: bash ${_drup_dir}/systemd/install-systemd.sh"
else
    bash "${_drup_dir}/systemd/install-systemd.sh"
fi

# --- 10. Post-process /etc/default/diretta-renderer ----------------------

# install-systemd.sh only copies the template when the conf doesn't exist;
# either way we (re)apply our three known variables idempotently.
_drup_set_conf_var() {
    local var="$1" val="$2"
    if [[ ! -f "$_DRUP_CONF_FILE" ]]; then
        return 0
    fi
    if grep -qE "^${var}=" "$_DRUP_CONF_FILE"; then
        sed -i -E "s|^${var}=.*$|${var}=\"${val}\"|" "$_DRUP_CONF_FILE"
    else
        echo "${var}=\"${val}\"" >> "$_DRUP_CONF_FILE"
    fi
}

log_info "Setting INTERFACE / TARGET_INTERFACE / TARGET in ${_DRUP_CONF_FILE}"
if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
    log_info "DRY-RUN: would set INTERFACE=${_drup_control_iface}, TARGET_INTERFACE=$([[ "$_drup_control_iface" == "$_drup_diretta_iface" ]] && echo '<empty: single NIC>' || echo "${_drup_diretta_iface}"), TARGET=1"
else
    _drup_set_conf_var INTERFACE "$_drup_control_iface"
    if [[ "$_drup_control_iface" == "$_drup_diretta_iface" ]]; then
        # Single-NIC: leave TARGET_INTERFACE empty so DRUP auto-detects.
        _drup_set_conf_var TARGET_INTERFACE ""
    else
        _drup_set_conf_var TARGET_INTERFACE "$_drup_diretta_iface"
    fi
    _drup_set_conf_var TARGET 1
fi

# --- 11. Enable the service (don't start — wait for reboot) --------------

run_cmd systemctl enable "$_DRUP_SERVICE"

log_info "DRUP installed. The service is enabled and will start at next reboot."
log_info "Review ${_DRUP_CONF_FILE} before reboot if you need to tune CPU affinity, IRQ pinning, buffers, etc."
