#!/bin/bash
#
# 11-install-slim2diretta — orchestrate the slim2Diretta install.
#
# Standalone (not coupled to 10-install-drup): a user may want only
# slim2Diretta. If 10 already configured the Diretta NIC + MTU (via a
# /etc/systemd/network/50-audiophile-*-mtu.link drop-in we own), this
# module detects it and offers to reuse the choice instead of re-prompting.
#
# Flow:
#   1. Detect SUDO_USER (slim2Diretta install.sh refuses root)
#   2. Find Diretta SDK under /home/$SUDO_USER/DirettaHostSDK_*
#   3. Install ethtool (used by start-slim2diretta at runtime)
#   4. Detect existing audiophile-setup .link file:
#        - present → propose 'Reuse iface X with MTU Y?' (default Y)
#        - absent → interactive NIC + MTU prompts, persist via .link
#          (and nmcli if NM is the live stack — same logic as module 10)
#   5. Ask optional LMS server IP (empty → auto-discover via Slimproto)
#   6. git clone slim2Diretta into $HOME/slim2Diretta (as $SUDO_USER)
#   7. Run ./install.sh as $SUDO_USER in a real TTY (interactive codec menu).
#      install.sh deploys /usr/local/bin/slim2diretta + service + conf itself.
#   8. Post-process /etc/default/slim2diretta: set TARGET, TARGET_INTERFACE,
#      optionally SLIM2DIRETTA_OPTS with the LMS IP.
#   9. systemctl enable (no start — service waits for next reboot).
#

set -euo pipefail

readonly _S2D_REPO_URL="https://github.com/cometdom/slim2Diretta.git"
readonly _S2D_CONF_FILE="/etc/default/slim2diretta"
readonly _S2D_SERVICE="slim2diretta.service"
readonly _S2D_GEN_TAG="# Generated by fedora-audiophile-setup"

log_step "Install slim2Diretta"

if ! ask_yes_no "Install slim2Diretta?" Y; then
    log_info "Skipping slim2Diretta install."
    return 0 2>/dev/null || exit 0
fi

# --- 1. Detect unprivileged user -----------------------------------------

if [[ -z "${SUDO_USER:-}" || "${SUDO_USER}" == "root" ]]; then
    log_error "slim2Diretta's install.sh refuses to run as root."
    log_error "Please launch this wizard via 'sudo' from a regular user account."
    exit 1
fi
_s2d_user="$SUDO_USER"
_s2d_home=$(getent passwd "$_s2d_user" | cut -d: -f6)
if [[ -z "$_s2d_home" || ! -d "$_s2d_home" ]]; then
    log_error "Cannot resolve home directory of user '${_s2d_user}'."
    exit 1
fi
log_info "slim2Diretta will be built as user '${_s2d_user}' (home: ${_s2d_home})."

# --- 2. Find the Diretta SDK ---------------------------------------------

_s2d_sdk=$(find "$_s2d_home" -maxdepth 1 -type d -name 'DirettaHostSDK_*' 2>/dev/null \
    | sort -V | tail -1)
if [[ -z "$_s2d_sdk" ]]; then
    log_error "Diretta SDK not found under ${_s2d_home}/DirettaHostSDK_*"
    log_error "Download manually from https://www.diretta.link/hostsdk.html (licence: personal use only),"
    log_error "extract it to ${_s2d_home}/, then re-run: sudo ./setup.sh --only install-slim2diretta"
    exit 1
fi
log_info "Found Diretta SDK: ${_s2d_sdk}"

# --- 3. Runtime prerequisite ---------------------------------------------

if ! has_package ethtool; then
    log_info "Installing ethtool (used by start-slim2diretta for link tuning)"
    run_cmd dnf -y install ethtool
fi

# --- 4. NIC + MTU: reuse existing audiophile-setup choice or prompt ------

_s2d_existing_link=$(find /etc/systemd/network -maxdepth 1 -name '50-audiophile-*-mtu.link' \
    -type f 2>/dev/null | head -1)

_s2d_diretta_iface=""
_s2d_mtu=""

if [[ -n "$_s2d_existing_link" ]]; then
    _s2d_existing_iface=$(basename "$_s2d_existing_link" | sed -E 's/^50-audiophile-(.+)-mtu\.link$/\1/')
    _s2d_existing_mtu=$(grep -oE '^MTUBytes=[0-9]+' "$_s2d_existing_link" | cut -d= -f2)
    log_info "Detected existing audiophile-setup NIC config: ${_s2d_existing_iface} @ MTU ${_s2d_existing_mtu}"
    if ask_yes_no "Reuse '${_s2d_existing_iface}' (MTU ${_s2d_existing_mtu}) as the Diretta NIC?" Y; then
        _s2d_diretta_iface="$_s2d_existing_iface"
        _s2d_mtu="$_s2d_existing_mtu"
    fi
fi

if [[ -z "$_s2d_diretta_iface" ]]; then
    # Same NIC discovery as module 10: list every physical ethernet, any link
    # state (Diretta target NIC often has carrier=down at install time).
    _s2d_eth_ifaces() {
        local sys iface typ
        for sys in /sys/class/net/*; do
            iface=$(basename "$sys")
            [[ "$iface" == "lo" ]] && continue
            [[ "$(readlink -f "$sys")" == *"/devices/virtual/"* ]] && continue
            typ=$(cat "${sys}/type" 2>/dev/null || echo "")
            [[ "$typ" == "1" ]] || continue
            echo "$iface"
        done
    }
    _s2d_describe_iface() {
        local iface="$1" state addr
        state=$(cat "/sys/class/net/${iface}/operstate" 2>/dev/null || echo "?")
        addr=$(ip -o -4 addr show dev "$iface" 2>/dev/null | awk '{print $4; exit}')
        if [[ -n "$addr" ]]; then
            printf '%s  (link %s, %s)' "$iface" "$state" "$addr"
        else
            printf '%s  (link %s, no IPv4)' "$iface" "$state"
        fi
    }

    mapfile -t _s2d_ifaces < <(_s2d_eth_ifaces)
    if [[ ${#_s2d_ifaces[@]} -eq 0 ]]; then
        log_error "No physical ethernet interface found — cannot configure slim2Diretta."
        exit 1
    elif [[ ${#_s2d_ifaces[@]} -eq 1 ]]; then
        _s2d_diretta_iface="${_s2d_ifaces[0]}"
        log_info "Single NIC '${_s2d_diretta_iface}' will be used as the Diretta NIC."
    else
        echo
        echo "Which NIC is connected to the Diretta target (audio side)?"
        local i
        for i in "${!_s2d_ifaces[@]}"; do
            printf "  %d) %s\n" "$((i+1))" "$(_s2d_describe_iface "${_s2d_ifaces[i]}")"
        done
        while true; do
            read -r -p "Number [1]: " _s2d_pick
            _s2d_pick="${_s2d_pick:-1}"
            if [[ "$_s2d_pick" =~ ^[1-9][0-9]*$ ]] && (( _s2d_pick >= 1 && _s2d_pick <= ${#_s2d_ifaces[@]} )); then
                _s2d_diretta_iface="${_s2d_ifaces[$((_s2d_pick-1))]}"
                break
            fi
            echo "Invalid choice."
        done
    fi

    echo
    echo "MTU on the Diretta NIC '${_s2d_diretta_iface}':"
    echo "  1) 1500   (standard)"
    echo "  2) 9014   (jumbo — recommended; matches Realtek RTL8156 and most jumbo-capable NICs)"
    echo "  3) 16128  (max — only if the Diretta target supports it)"
    read -r -p "Number [2]: " _s2d_mtu_choice
    case "${_s2d_mtu_choice:-2}" in
        1) _s2d_mtu=1500 ;;
        2|"") _s2d_mtu=9014 ;;
        3) _s2d_mtu=16128 ;;
        *) log_error "Invalid MTU choice: ${_s2d_mtu_choice}"; exit 1 ;;
    esac

    # Persist via .link drop-in (+ nmcli if NM active) — same logic as module 10.
    _s2d_link_file="/etc/systemd/network/50-audiophile-${_s2d_diretta_iface}-mtu.link"
    log_info "Writing ${_s2d_link_file} (MTUBytes=${_s2d_mtu})"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_s2d_link_file}"
    else
        mkdir -p /etc/systemd/network
        cat > "$_s2d_link_file" <<EOF
${_S2D_GEN_TAG}
[Match]
OriginalName=${_s2d_diretta_iface}

[Link]
MTUBytes=${_s2d_mtu}
EOF
    fi
    if is_service_active NetworkManager && command -v nmcli >/dev/null 2>&1; then
        _s2d_conn=$(nmcli -t -f NAME,DEVICE connection show --active 2>/dev/null \
            | awk -F: -v d="$_s2d_diretta_iface" '$2==d {print $1; exit}')
        if [[ -n "$_s2d_conn" ]]; then
            log_info "Setting MTU ${_s2d_mtu} on NetworkManager connection '${_s2d_conn}'"
            run_cmd nmcli connection modify "$_s2d_conn" 802-3-ethernet.mtu "$_s2d_mtu"
        else
            log_warn "No active NM connection found for ${_s2d_diretta_iface}; relying on the udev .link drop-in only."
        fi
    fi
fi

# --- 5. Optional LMS server IP -------------------------------------------

echo
read -r -p "LMS server IP (leave empty for Slimproto auto-discovery): " _s2d_lms_ip
if [[ -n "${_s2d_lms_ip}" ]]; then
    _s2d_opts="-s ${_s2d_lms_ip}"
    log_info "slim2Diretta will connect to LMS at ${_s2d_lms_ip}."
else
    _s2d_opts=""
    log_info "slim2Diretta will auto-discover the LMS server."
fi

# --- 6. Clone slim2Diretta as the user -----------------------------------

_s2d_dir="${_s2d_home}/slim2Diretta"
if [[ -d "${_s2d_dir}/.git" ]]; then
    log_info "slim2Diretta repo already cloned at ${_s2d_dir}"
else
    log_info "Cloning slim2Diretta repo to ${_s2d_dir} (as ${_s2d_user})"
    run_cmd sudo -u "$_s2d_user" git clone "$_S2D_REPO_URL" "$_s2d_dir"
fi

# --- 7. Run install.sh as the user (TTY-direct) --------------------------

_s2d_binary="/usr/local/bin/slim2diretta"
if [[ -x "$_s2d_binary" ]]; then
    log_info "slim2Diretta binary already installed at ${_s2d_binary} — skipping ./install.sh."
else
    log_warn "About to run slim2Diretta ./install.sh as user '${_s2d_user}'."
    log_warn "Answer its interactive prompts (codec selection menu, etc.)."
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would execute as ${_s2d_user}: cd ${_s2d_dir} && ./install.sh"
    else
        sudo -u "$_s2d_user" -i bash -c "cd '${_s2d_dir}' && ./install.sh"
    fi
fi

# --- 8. Post-process /etc/default/slim2diretta ---------------------------

_s2d_set_conf_var() {
    local var="$1" val="$2"
    if [[ ! -f "$_S2D_CONF_FILE" ]]; then
        return 0
    fi
    if grep -qE "^${var}=" "$_S2D_CONF_FILE"; then
        sed -i -E "s|^${var}=.*$|${var}=\"${val}\"|" "$_S2D_CONF_FILE"
    else
        echo "${var}=\"${val}\"" >> "$_S2D_CONF_FILE"
    fi
}

log_info "Setting TARGET / TARGET_INTERFACE${_s2d_opts:+ / SLIM2DIRETTA_OPTS} in ${_S2D_CONF_FILE}"
if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
    log_info "DRY-RUN: would set TARGET=1, TARGET_INTERFACE=${_s2d_diretta_iface}${_s2d_opts:+, SLIM2DIRETTA_OPTS=${_s2d_opts}}"
else
    _s2d_set_conf_var TARGET 1
    _s2d_set_conf_var TARGET_INTERFACE "$_s2d_diretta_iface"
    if [[ -n "$_s2d_opts" ]]; then
        _s2d_set_conf_var SLIM2DIRETTA_OPTS "$_s2d_opts"
    fi
fi

# --- 9. Enable service (don't start — wait for reboot) -------------------

run_cmd systemctl enable "$_S2D_SERVICE"

log_info "slim2Diretta installed. The service is enabled and will start at next reboot."
log_info "Review ${_S2D_CONF_FILE} before reboot to tune player name, codec options, CPU affinity, etc."
