#!/bin/bash
#
# diretta-net-toggle.sh — switch a Diretta host's two NICs between:
#
#   independent  enp5s0 = LAN (DHCP), enp4s0 = Diretta link (link-local
#                only, L2). The normal audiophile operating mode.
#
#   bridge       enp5s0 + enp4s0 enslaved into a bridge that takes the LAN
#                DHCP lease. The Diretta target (cabled to enp4s0) then
#                sits on the LAN segment and is reachable from any LAN
#                host — handy to check/apply a target firmware update
#                WITHOUT unplugging and recabling it onto a switch.
#
# systemd-networkd ONLY (this is the "first step" implementation; a
# NetworkManager variant could come later). The bridge mode is TRANSIENT:
# it is pinned to MTU 1500 for LAN compatibility. Switch back to
# 'independent' for listening — the jumbo udev .link on the Diretta NIC
# then applies again.
#
# Usage:
#   sudo ./scripts/diretta-net-toggle.sh status
#   sudo ./scripts/diretta-net-toggle.sh bridge
#   sudo ./scripts/diretta-net-toggle.sh independent
#
# Interface names default to enp5s0 / enp4s0; override via env:
#   DIRETTA_LAN_IFACE=...  DIRETTA_TARGET_IFACE=...
#
# WARNING: this reconfigures the network. Switching to/from 'bridge'
# moves the LAN IP between enp5s0 and the bridge, so an SSH session over
# the LAN WILL drop briefly — prefer a local console, or reconnect after
# (the DHCP lease is usually re-issued to the same address).
#

set -euo pipefail

LAN_IFACE="${DIRETTA_LAN_IFACE:-enp5s0}"
DIRETTA_IFACE="${DIRETTA_TARGET_IFACE:-enp4s0}"
BRIDGE="diretta-br0"
NETDIR="/etc/systemd/network"
TAG="# Managed by diretta-net-toggle"

_info()  { echo "[net-toggle] $*"; }
_warn()  { echo "[net-toggle] WARNING: $*" >&2; }
_err()   { echo "[net-toggle] ERROR: $*" >&2; }

_require_root() {
    if [[ $EUID -ne 0 ]]; then
        _err "must run as root (use sudo)."
        exit 1
    fi
}

_require_networkd() {
    if ! systemctl is-active --quiet systemd-networkd; then
        _err "systemd-networkd is not active. This tool only supports systemd-networkd."
        _err "(If you are on NetworkManager, this script does not apply — see docs.)"
        exit 1
    fi
}

# A managed file is one whose first line is our TAG.
_is_managed() {
    [[ -f "$1" ]] && [[ "$(head -1 "$1" 2>/dev/null)" == "$TAG" ]]
}

# Candidate files this tool may have written.
_managed_candidates() {
    printf '%s\n' \
        "${NETDIR}/10-${LAN_IFACE}.network" \
        "${NETDIR}/10-${DIRETTA_IFACE}.network" \
        "${NETDIR}/15-${BRIDGE}.netdev" \
        "${NETDIR}/20-${BRIDGE}.network"
}

_clean_managed() {
    local f
    while IFS= read -r f; do
        if _is_managed "$f"; then
            _info "removing ${f}"
            rm -f "$f"
        fi
    done < <(_managed_candidates)
}

_current_mode() {
    if _is_managed "${NETDIR}/15-${BRIDGE}.netdev"; then
        echo "bridge"
    elif _is_managed "${NETDIR}/10-${LAN_IFACE}.network"; then
        echo "independent"
    else
        echo "unknown"
    fi
}

_warn_unmanaged_conflicts() {
    # The wizard's module 03 (network-stack → S) writes
    # 10-<iface>.network tagged "# Generated by fedora-audiophile-setup".
    # We overwrite those names; warn so the user knows this tool takes over.
    local f
    for f in "${NETDIR}/10-${LAN_IFACE}.network" "${NETDIR}/10-${DIRETTA_IFACE}.network"; do
        if [[ -f "$f" ]] && ! _is_managed "$f"; then
            _warn "${f} exists and is NOT managed by this tool (likely the wizard's). It will be overwritten; 'independent' restores a working Diretta config."
        fi
    done
}

_write_independent() {
    cat > "${NETDIR}/10-${LAN_IFACE}.network" <<EOF
${TAG}
[Match]
Name=${LAN_IFACE}

[Network]
DHCP=yes
EOF
    cat > "${NETDIR}/10-${DIRETTA_IFACE}.network" <<EOF
${TAG}
[Match]
Name=${DIRETTA_IFACE}

[Network]
# Diretta speaks L2 on this link — no routable IP needed. The target may
# be powered off at boot, so configure the iface even without carrier.
LinkLocalAddressing=yes
ConfigureWithoutCarrier=yes
EOF
}

_write_bridge() {
    cat > "${NETDIR}/15-${BRIDGE}.netdev" <<EOF
${TAG}
[NetDev]
Name=${BRIDGE}
Kind=bridge
EOF
    # Ports pinned to 1500 so the bridged segment is LAN-compatible
    # (the Diretta NIC's jumbo udev .link is overridden while bridged).
    cat > "${NETDIR}/10-${LAN_IFACE}.network" <<EOF
${TAG}
[Match]
Name=${LAN_IFACE}

[Network]
Bridge=${BRIDGE}

[Link]
MTUBytes=1500
EOF
    cat > "${NETDIR}/10-${DIRETTA_IFACE}.network" <<EOF
${TAG}
[Match]
Name=${DIRETTA_IFACE}

[Network]
Bridge=${BRIDGE}

[Link]
MTUBytes=1500
EOF
    cat > "${NETDIR}/20-${BRIDGE}.network" <<EOF
${TAG}
[Match]
Name=${BRIDGE}

[Network]
DHCP=yes

[Link]
MTUBytes=1500
EOF
}

_apply() {
    _info "reloading systemd-networkd…"
    networkctl reload 2>/dev/null || true
    systemctl restart systemd-networkd
    _info "done. Give it a few seconds; if you were on SSH over the LAN, reconnect."
}

_confirm() {
    local prompt="$1" ans
    read -r -p "${prompt} [y/N] " ans
    [[ "$ans" =~ ^[Yy]$ ]]
}

cmd_status() {
    echo "Mode (per managed files): $(_current_mode)"
    echo
    echo "Managed files present:"
    local f any=0
    while IFS= read -r f; do
        if _is_managed "$f"; then echo "  $f"; any=1; fi
    done < <(_managed_candidates)
    [[ $any -eq 0 ]] && echo "  (none — network not managed by this tool)"
    echo
    echo "Interfaces:"
    ip -br addr show "$LAN_IFACE" 2>/dev/null || true
    ip -br addr show "$DIRETTA_IFACE" 2>/dev/null || true
    ip -br addr show "$BRIDGE" 2>/dev/null || true
    echo
    networkctl --no-pager status "$LAN_IFACE" "$DIRETTA_IFACE" 2>/dev/null \
        | sed -n '1,12p' || true
}

cmd_switch() {
    local target="$1"
    _require_root
    _require_networkd
    local cur; cur=$(_current_mode)
    if [[ "$cur" == "$target" ]]; then
        _info "already in '${target}' mode (per managed files)."
        if ! _confirm "Re-apply '${target}' anyway?"; then
            _info "nothing to do."
            return 0
        fi
    fi
    _warn_unmanaged_conflicts
    _warn "this will restart systemd-networkd. An SSH session over ${LAN_IFACE} may drop."
    if ! _confirm "Switch to '${target}' now?"; then
        _info "aborted."
        return 0
    fi
    _clean_managed
    case "$target" in
        independent) _write_independent ;;
        bridge)      _write_bridge ;;
    esac
    _apply
    echo
    cmd_status
}

main() {
    case "${1:-}" in
        status)             cmd_status ;;
        bridge|independent) cmd_switch "$1" ;;
        *)
            cat >&2 <<EOF
Usage: sudo $0 {status|bridge|independent}

  status        show the current mode and interface state (read-only)
  bridge        enslave ${LAN_IFACE}+${DIRETTA_IFACE} into ${BRIDGE} (LAN
                DHCP, MTU 1500) — target reachable from the LAN, TRANSIENT
  independent   ${LAN_IFACE}=LAN DHCP, ${DIRETTA_IFACE}=Diretta link-local
                — the normal audiophile mode

Override iface names: DIRETTA_LAN_IFACE=... DIRETTA_TARGET_IFACE=...
EOF
            exit 2
            ;;
    esac
}

main "$@"
